import { describe, expect, it } from "vitest"

import { calendarEpisodeResource } from "./compatCalendarResources"

describe("compatible calendar resources", () => {
  it("maps local calendar episodes to Sonarr-style episode resources", () => {
    expect(
      calendarEpisodeResource({
        episode: {
          id: 3,
          seasonId: 2,
          tvdbId: 300,
          tmdbId: null,
          title: "Pilot",
          episodeNumber: 1,
          absoluteEpisodeNumber: null,
          airDate: new Date("2026-02-15T10:00:00.000Z"),
          overview: "First episode",
          runtimeMinutes: 45,
          hasFile: false,
          filePath: null,
          monitored: true,
          existingQualityName: null,
          existingQualityRank: null,
          existingFormatScore: null,
          existingRevisionVersion: 1,
          existingRevisionReal: 0,
          existingReleaseGroup: null,
        },
        season: { id: 2, seriesId: 1, tmdbId: null, seasonNumber: 1, monitored: true },
        series: {
          id: 1,
          tvdbId: 100,
          tmdbId: 200,
          imdbId: "tt1234567",
          title: "The Show",
          originalTitle: null,
          year: 2026,
          overview: "Series overview",
          posterPath: "/poster.jpg",
          status: "continuing",
          network: "Network",
          genres: ["Drama"],
          tags: ["favorite"],
          runtimeMinutes: 45,
          seriesType: "standard",
          certification: "TV-14",
          rootFolderPath: "/media/tv",
          monitored: true,
          qualityProfileId: 4,
          seasonFolder: true,
          metadataRefreshedAt: null,
          addedAt: new Date("2026-01-01T00:00:00.000Z"),
        },
      }),
    ).toMatchObject({
      id: 3,
      seriesId: 1,
      tvdbId: 300,
      episodeFileId: 0,
      seasonNumber: 1,
      episodeNumber: 1,
      title: "Pilot",
      airDate: "2026-02-15",
      airDateUtc: "2026-02-15T10:00:00.000Z",
      runtime: 45,
      overview: "First episode",
      hasFile: false,
      monitored: true,
      endTime: "2026-02-15T10:45:00.000Z",
      series: null,
      images: [],
    })
  })

  it("includes a minimal compatible series resource when requested", () => {
    const resource = calendarEpisodeResource(
      {
        episode: {
          id: 4,
          seasonId: 2,
          tvdbId: 301,
          tmdbId: null,
          title: "Second",
          episodeNumber: 2,
          absoluteEpisodeNumber: 12,
          airDate: null,
          overview: null,
          runtimeMinutes: null,
          hasFile: true,
          filePath: "/media/tv/show/s01e02.mkv",
          monitored: false,
          existingQualityName: null,
          existingQualityRank: null,
          existingFormatScore: null,
          existingRevisionVersion: 1,
          existingRevisionReal: 0,
          existingReleaseGroup: null,
        },
        season: { id: 2, seriesId: 1, tmdbId: null, seasonNumber: 1, monitored: true },
        series: {
          id: 1,
          tvdbId: 100,
          tmdbId: null,
          imdbId: null,
          title: "Another Show",
          originalTitle: null,
          year: null,
          overview: null,
          posterPath: null,
          status: "ended",
          network: null,
          genres: [],
          tags: [],
          runtimeMinutes: 30,
          seriesType: null,
          certification: null,
          rootFolderPath: null,
          monitored: false,
          qualityProfileId: null,
          seasonFolder: true,
          metadataRefreshedAt: null,
          addedAt: new Date("2026-01-01T00:00:00.000Z"),
        },
      },
      { includeSeries: true },
    )

    expect(resource).toMatchObject({
      episodeFileId: 4,
      runtime: 30,
      monitored: false,
      absoluteEpisodeNumber: 12,
      series: {
        id: 1,
        title: "Another Show",
        sortTitle: "another show",
        status: "ended",
        tvdbId: 100,
        seriesType: "standard",
        titleSlug: "another-show",
      },
    })
  })
})
