/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/system'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvIndexRouteImport } from './routes/tv/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as MoviesIndexRouteImport } from './routes/movies/index'
import { Route as ActivityIndexRouteImport } from './routes/activity/index'
import { Route as TvIdRouteImport } from './routes/tv/$id'
import { Route as SettingsTagsRouteImport } from './routes/settings/tags'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsSchedulerRouteImport } from './routes/settings/scheduler'
import { Route as SettingsProfilesRouteImport } from './routes/settings/profiles'
import { Route as SettingsPluginsRouteImport } from './routes/settings/plugins'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsMediaServersRouteImport } from './routes/settings/media-servers'
import { Route as SettingsMediaManagementRouteImport } from './routes/settings/media-management'
import { Route as SettingsIndexersRouteImport } from './routes/settings/indexers'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'
import { Route as SettingsDownloadClientsRouteImport } from './routes/settings/download-clients'
import { Route as OnboardingWizardRouteImport } from './routes/onboarding/wizard'
import { Route as OnboardingQuickstartRouteImport } from './routes/onboarding/quickstart'
import { Route as MoviesIdRouteImport } from './routes/movies/$id'
import { Route as ApiQueueRouteImport } from './routes/api.queue'
import { Route as ActivityUsersRouteImport } from './routes/activity/users'
import { Route as ActivityStatsRouteImport } from './routes/activity/stats'
import { Route as ActivityQueueRouteImport } from './routes/activity/queue'
import { Route as ActivityHistoryRouteImport } from './routes/activity/history'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiSystemTasksRouteImport } from './routes/api.system.tasks'
import { Route as ApiSystemStatusRouteImport } from './routes/api.system.status'
import { Route as ApiSystemLogsRouteImport } from './routes/api.system.logs'
import { Route as ApiSystemHealthRouteImport } from './routes/api.system.health'
import { Route as ApiVersionTagRouteImport } from './routes/api.$version.tag'
import { Route as ApiVersionRootfolderRouteImport } from './routes/api.$version.rootfolder'
import { Route as ApiVersionQueueRouteImport } from './routes/api.$version.queue'
import { Route as ApiVersionQualityprofileRouteImport } from './routes/api.$version.qualityprofile'
import { Route as ApiVersionHealthRouteImport } from './routes/api.$version.health'
import { Route as ApiVersionCustomformatRouteImport } from './routes/api.$version.customformat'
import { Route as ApiVersionCalendarRouteImport } from './routes/api.$version.calendar'
import { Route as ApiQueueIdRetryRouteImport } from './routes/api.queue.$id.retry'
import { Route as ApiQueueIdRemoveRouteImport } from './routes/api.queue.$id.remove'
import { Route as ApiQueueIdBlocklistRouteImport } from './routes/api.queue.$id.blocklist'
import { Route as ApiIndexersAggregateProtocolRouteImport } from './routes/api.indexers.aggregate.$protocol'
import { Route as ApiVersionTagDetailRouteImport } from './routes/api.$version.tag.detail'
import { Route as ApiVersionTagIdRouteImport } from './routes/api.$version.tag.$id'
import { Route as ApiVersionSystemStatusRouteImport } from './routes/api.$version.system.status'
import { Route as ApiVersionRootfolderIdRouteImport } from './routes/api.$version.rootfolder.$id'
import { Route as ApiVersionQueueStatusRouteImport } from './routes/api.$version.queue.status'
import { Route as ApiVersionQueueDetailsRouteImport } from './routes/api.$version.queue.details'
import { Route as ApiVersionQueueIdRouteImport } from './routes/api.$version.queue.$id'
import { Route as ApiVersionQualityprofileIdRouteImport } from './routes/api.$version.qualityprofile.$id'
import { Route as ApiVersionCustomformatIdRouteImport } from './routes/api.$version.customformat.$id'
import { Route as ApiVersionCalendarIdRouteImport } from './routes/api.$version.calendar.$id'
import { Route as ApiSystemBackupsIdDownloadRouteImport } from './routes/api.system.backups.$id.download'
import { Route as ApiIndexersAggregateProtocolApiRouteImport } from './routes/api.indexers.aggregate.$protocol.api'
import { Route as ApiVersionTagDetailIdRouteImport } from './routes/api.$version.tag.detail.$id'

const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIndexRoute = TvIndexRouteImport.update({
  id: '/tv/',
  path: '/tv/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIdRoute = TvIdRouteImport.update({
  id: '/tv/$id',
  path: '/tv/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTagsRoute = SettingsTagsRouteImport.update({
  id: '/settings/tags',
  path: '/settings/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSchedulerRoute = SettingsSchedulerRouteImport.update({
  id: '/settings/scheduler',
  path: '/settings/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfilesRoute = SettingsProfilesRouteImport.update({
  id: '/settings/profiles',
  path: '/settings/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPluginsRoute = SettingsPluginsRouteImport.update({
  id: '/settings/plugins',
  path: '/settings/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMediaServersRoute = SettingsMediaServersRouteImport.update({
  id: '/settings/media-servers',
  path: '/settings/media-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMediaManagementRoute = SettingsMediaManagementRouteImport.update({
  id: '/settings/media-management',
  path: '/settings/media-management',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexersRoute = SettingsIndexersRouteImport.update({
  id: '/settings/indexers',
  path: '/settings/indexers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDownloadClientsRoute = SettingsDownloadClientsRouteImport.update({
  id: '/settings/download-clients',
  path: '/settings/download-clients',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWizardRoute = OnboardingWizardRouteImport.update({
  id: '/onboarding/wizard',
  path: '/onboarding/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingQuickstartRoute = OnboardingQuickstartRouteImport.update({
  id: '/onboarding/quickstart',
  path: '/onboarding/quickstart',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIdRoute = MoviesIdRouteImport.update({
  id: '/movies/$id',
  path: '/movies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueueRoute = ApiQueueRouteImport.update({
  id: '/api/queue',
  path: '/api/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityUsersRoute = ActivityUsersRouteImport.update({
  id: '/activity/users',
  path: '/activity/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityStatsRoute = ActivityStatsRouteImport.update({
  id: '/activity/stats',
  path: '/activity/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityQueueRoute = ActivityQueueRouteImport.update({
  id: '/activity/queue',
  path: '/activity/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityHistoryRoute = ActivityHistoryRouteImport.update({
  id: '/activity/history',
  path: '/activity/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemTasksRoute = ApiSystemTasksRouteImport.update({
  id: '/api/system/tasks',
  path: '/api/system/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemStatusRoute = ApiSystemStatusRouteImport.update({
  id: '/api/system/status',
  path: '/api/system/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemLogsRoute = ApiSystemLogsRouteImport.update({
  id: '/api/system/logs',
  path: '/api/system/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemHealthRoute = ApiSystemHealthRouteImport.update({
  id: '/api/system/health',
  path: '/api/system/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionTagRoute = ApiVersionTagRouteImport.update({
  id: '/api/$version/tag',
  path: '/api/$version/tag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRootfolderRoute = ApiVersionRootfolderRouteImport.update({
  id: '/api/$version/rootfolder',
  path: '/api/$version/rootfolder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionQueueRoute = ApiVersionQueueRouteImport.update({
  id: '/api/$version/queue',
  path: '/api/$version/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionQualityprofileRoute =
  ApiVersionQualityprofileRouteImport.update({
    id: '/api/$version/qualityprofile',
    path: '/api/$version/qualityprofile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiVersionHealthRoute = ApiVersionHealthRouteImport.update({
  id: '/api/$version/health',
  path: '/api/$version/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionCustomformatRoute = ApiVersionCustomformatRouteImport.update({
  id: '/api/$version/customformat',
  path: '/api/$version/customformat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionCalendarRoute = ApiVersionCalendarRouteImport.update({
  id: '/api/$version/calendar',
  path: '/api/$version/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueueIdRetryRoute = ApiQueueIdRetryRouteImport.update({
  id: '/$id/retry',
  path: '/$id/retry',
  getParentRoute: () => ApiQueueRoute,
} as any)
const ApiQueueIdRemoveRoute = ApiQueueIdRemoveRouteImport.update({
  id: '/$id/remove',
  path: '/$id/remove',
  getParentRoute: () => ApiQueueRoute,
} as any)
const ApiQueueIdBlocklistRoute = ApiQueueIdBlocklistRouteImport.update({
  id: '/$id/blocklist',
  path: '/$id/blocklist',
  getParentRoute: () => ApiQueueRoute,
} as any)
const ApiIndexersAggregateProtocolRoute =
  ApiIndexersAggregateProtocolRouteImport.update({
    id: '/api/indexers/aggregate/$protocol',
    path: '/api/indexers/aggregate/$protocol',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiVersionTagDetailRoute = ApiVersionTagDetailRouteImport.update({
  id: '/detail',
  path: '/detail',
  getParentRoute: () => ApiVersionTagRoute,
} as any)
const ApiVersionTagIdRoute = ApiVersionTagIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiVersionTagRoute,
} as any)
const ApiVersionSystemStatusRoute = ApiVersionSystemStatusRouteImport.update({
  id: '/api/$version/system/status',
  path: '/api/$version/system/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRootfolderIdRoute = ApiVersionRootfolderIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiVersionRootfolderRoute,
} as any)
const ApiVersionQueueStatusRoute = ApiVersionQueueStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiVersionQueueRoute,
} as any)
const ApiVersionQueueDetailsRoute = ApiVersionQueueDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => ApiVersionQueueRoute,
} as any)
const ApiVersionQueueIdRoute = ApiVersionQueueIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiVersionQueueRoute,
} as any)
const ApiVersionQualityprofileIdRoute =
  ApiVersionQualityprofileIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiVersionQualityprofileRoute,
  } as any)
const ApiVersionCustomformatIdRoute =
  ApiVersionCustomformatIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiVersionCustomformatRoute,
  } as any)
const ApiVersionCalendarIdRoute = ApiVersionCalendarIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiVersionCalendarRoute,
} as any)
const ApiSystemBackupsIdDownloadRoute =
  ApiSystemBackupsIdDownloadRouteImport.update({
    id: '/api/system/backups/$id/download',
    path: '/api/system/backups/$id/download',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIndexersAggregateProtocolApiRoute =
  ApiIndexersAggregateProtocolApiRouteImport.update({
    id: '/api',
    path: '/api',
    getParentRoute: () => ApiIndexersAggregateProtocolRoute,
  } as any)
const ApiVersionTagDetailIdRoute = ApiVersionTagDetailIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiVersionTagDetailRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/system': typeof SystemRoute
  '/activity/history': typeof ActivityHistoryRoute
  '/activity/queue': typeof ActivityQueueRoute
  '/activity/stats': typeof ActivityStatsRoute
  '/activity/users': typeof ActivityUsersRoute
  '/api/queue': typeof ApiQueueRouteWithChildren
  '/movies/$id': typeof MoviesIdRoute
  '/onboarding/quickstart': typeof OnboardingQuickstartRoute
  '/onboarding/wizard': typeof OnboardingWizardRoute
  '/settings/download-clients': typeof SettingsDownloadClientsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/indexers': typeof SettingsIndexersRoute
  '/settings/media-management': typeof SettingsMediaManagementRoute
  '/settings/media-servers': typeof SettingsMediaServersRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/settings/profiles': typeof SettingsProfilesRoute
  '/settings/scheduler': typeof SettingsSchedulerRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/tags': typeof SettingsTagsRoute
  '/tv/$id': typeof TvIdRoute
  '/activity/': typeof ActivityIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tv/': typeof TvIndexRoute
  '/api/$version/calendar': typeof ApiVersionCalendarRouteWithChildren
  '/api/$version/customformat': typeof ApiVersionCustomformatRouteWithChildren
  '/api/$version/health': typeof ApiVersionHealthRoute
  '/api/$version/qualityprofile': typeof ApiVersionQualityprofileRouteWithChildren
  '/api/$version/queue': typeof ApiVersionQueueRouteWithChildren
  '/api/$version/rootfolder': typeof ApiVersionRootfolderRouteWithChildren
  '/api/$version/tag': typeof ApiVersionTagRouteWithChildren
  '/api/system/health': typeof ApiSystemHealthRoute
  '/api/system/logs': typeof ApiSystemLogsRoute
  '/api/system/status': typeof ApiSystemStatusRoute
  '/api/system/tasks': typeof ApiSystemTasksRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/$version/calendar/$id': typeof ApiVersionCalendarIdRoute
  '/api/$version/customformat/$id': typeof ApiVersionCustomformatIdRoute
  '/api/$version/qualityprofile/$id': typeof ApiVersionQualityprofileIdRoute
  '/api/$version/queue/$id': typeof ApiVersionQueueIdRoute
  '/api/$version/queue/details': typeof ApiVersionQueueDetailsRoute
  '/api/$version/queue/status': typeof ApiVersionQueueStatusRoute
  '/api/$version/rootfolder/$id': typeof ApiVersionRootfolderIdRoute
  '/api/$version/system/status': typeof ApiVersionSystemStatusRoute
  '/api/$version/tag/$id': typeof ApiVersionTagIdRoute
  '/api/$version/tag/detail': typeof ApiVersionTagDetailRouteWithChildren
  '/api/indexers/aggregate/$protocol': typeof ApiIndexersAggregateProtocolRouteWithChildren
  '/api/queue/$id/blocklist': typeof ApiQueueIdBlocklistRoute
  '/api/queue/$id/remove': typeof ApiQueueIdRemoveRoute
  '/api/queue/$id/retry': typeof ApiQueueIdRetryRoute
  '/api/$version/tag/detail/$id': typeof ApiVersionTagDetailIdRoute
  '/api/indexers/aggregate/$protocol/api': typeof ApiIndexersAggregateProtocolApiRoute
  '/api/system/backups/$id/download': typeof ApiSystemBackupsIdDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/system': typeof SystemRoute
  '/activity/history': typeof ActivityHistoryRoute
  '/activity/queue': typeof ActivityQueueRoute
  '/activity/stats': typeof ActivityStatsRoute
  '/activity/users': typeof ActivityUsersRoute
  '/api/queue': typeof ApiQueueRouteWithChildren
  '/movies/$id': typeof MoviesIdRoute
  '/onboarding/quickstart': typeof OnboardingQuickstartRoute
  '/onboarding/wizard': typeof OnboardingWizardRoute
  '/settings/download-clients': typeof SettingsDownloadClientsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/indexers': typeof SettingsIndexersRoute
  '/settings/media-management': typeof SettingsMediaManagementRoute
  '/settings/media-servers': typeof SettingsMediaServersRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/settings/profiles': typeof SettingsProfilesRoute
  '/settings/scheduler': typeof SettingsSchedulerRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/tags': typeof SettingsTagsRoute
  '/tv/$id': typeof TvIdRoute
  '/activity': typeof ActivityIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tv': typeof TvIndexRoute
  '/api/$version/calendar': typeof ApiVersionCalendarRouteWithChildren
  '/api/$version/customformat': typeof ApiVersionCustomformatRouteWithChildren
  '/api/$version/health': typeof ApiVersionHealthRoute
  '/api/$version/qualityprofile': typeof ApiVersionQualityprofileRouteWithChildren
  '/api/$version/queue': typeof ApiVersionQueueRouteWithChildren
  '/api/$version/rootfolder': typeof ApiVersionRootfolderRouteWithChildren
  '/api/$version/tag': typeof ApiVersionTagRouteWithChildren
  '/api/system/health': typeof ApiSystemHealthRoute
  '/api/system/logs': typeof ApiSystemLogsRoute
  '/api/system/status': typeof ApiSystemStatusRoute
  '/api/system/tasks': typeof ApiSystemTasksRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/$version/calendar/$id': typeof ApiVersionCalendarIdRoute
  '/api/$version/customformat/$id': typeof ApiVersionCustomformatIdRoute
  '/api/$version/qualityprofile/$id': typeof ApiVersionQualityprofileIdRoute
  '/api/$version/queue/$id': typeof ApiVersionQueueIdRoute
  '/api/$version/queue/details': typeof ApiVersionQueueDetailsRoute
  '/api/$version/queue/status': typeof ApiVersionQueueStatusRoute
  '/api/$version/rootfolder/$id': typeof ApiVersionRootfolderIdRoute
  '/api/$version/system/status': typeof ApiVersionSystemStatusRoute
  '/api/$version/tag/$id': typeof ApiVersionTagIdRoute
  '/api/$version/tag/detail': typeof ApiVersionTagDetailRouteWithChildren
  '/api/indexers/aggregate/$protocol': typeof ApiIndexersAggregateProtocolRouteWithChildren
  '/api/queue/$id/blocklist': typeof ApiQueueIdBlocklistRoute
  '/api/queue/$id/remove': typeof ApiQueueIdRemoveRoute
  '/api/queue/$id/retry': typeof ApiQueueIdRetryRoute
  '/api/$version/tag/detail/$id': typeof ApiVersionTagDetailIdRoute
  '/api/indexers/aggregate/$protocol/api': typeof ApiIndexersAggregateProtocolApiRoute
  '/api/system/backups/$id/download': typeof ApiSystemBackupsIdDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/system': typeof SystemRoute
  '/activity/history': typeof ActivityHistoryRoute
  '/activity/queue': typeof ActivityQueueRoute
  '/activity/stats': typeof ActivityStatsRoute
  '/activity/users': typeof ActivityUsersRoute
  '/api/queue': typeof ApiQueueRouteWithChildren
  '/movies/$id': typeof MoviesIdRoute
  '/onboarding/quickstart': typeof OnboardingQuickstartRoute
  '/onboarding/wizard': typeof OnboardingWizardRoute
  '/settings/download-clients': typeof SettingsDownloadClientsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/indexers': typeof SettingsIndexersRoute
  '/settings/media-management': typeof SettingsMediaManagementRoute
  '/settings/media-servers': typeof SettingsMediaServersRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/settings/profiles': typeof SettingsProfilesRoute
  '/settings/scheduler': typeof SettingsSchedulerRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/tags': typeof SettingsTagsRoute
  '/tv/$id': typeof TvIdRoute
  '/activity/': typeof ActivityIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tv/': typeof TvIndexRoute
  '/api/$version/calendar': typeof ApiVersionCalendarRouteWithChildren
  '/api/$version/customformat': typeof ApiVersionCustomformatRouteWithChildren
  '/api/$version/health': typeof ApiVersionHealthRoute
  '/api/$version/qualityprofile': typeof ApiVersionQualityprofileRouteWithChildren
  '/api/$version/queue': typeof ApiVersionQueueRouteWithChildren
  '/api/$version/rootfolder': typeof ApiVersionRootfolderRouteWithChildren
  '/api/$version/tag': typeof ApiVersionTagRouteWithChildren
  '/api/system/health': typeof ApiSystemHealthRoute
  '/api/system/logs': typeof ApiSystemLogsRoute
  '/api/system/status': typeof ApiSystemStatusRoute
  '/api/system/tasks': typeof ApiSystemTasksRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/$version/calendar/$id': typeof ApiVersionCalendarIdRoute
  '/api/$version/customformat/$id': typeof ApiVersionCustomformatIdRoute
  '/api/$version/qualityprofile/$id': typeof ApiVersionQualityprofileIdRoute
  '/api/$version/queue/$id': typeof ApiVersionQueueIdRoute
  '/api/$version/queue/details': typeof ApiVersionQueueDetailsRoute
  '/api/$version/queue/status': typeof ApiVersionQueueStatusRoute
  '/api/$version/rootfolder/$id': typeof ApiVersionRootfolderIdRoute
  '/api/$version/system/status': typeof ApiVersionSystemStatusRoute
  '/api/$version/tag/$id': typeof ApiVersionTagIdRoute
  '/api/$version/tag/detail': typeof ApiVersionTagDetailRouteWithChildren
  '/api/indexers/aggregate/$protocol': typeof ApiIndexersAggregateProtocolRouteWithChildren
  '/api/queue/$id/blocklist': typeof ApiQueueIdBlocklistRoute
  '/api/queue/$id/remove': typeof ApiQueueIdRemoveRoute
  '/api/queue/$id/retry': typeof ApiQueueIdRetryRoute
  '/api/$version/tag/detail/$id': typeof ApiVersionTagDetailIdRoute
  '/api/indexers/aggregate/$protocol/api': typeof ApiIndexersAggregateProtocolApiRoute
  '/api/system/backups/$id/download': typeof ApiSystemBackupsIdDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/login'
    | '/system'
    | '/activity/history'
    | '/activity/queue'
    | '/activity/stats'
    | '/activity/users'
    | '/api/queue'
    | '/movies/$id'
    | '/onboarding/quickstart'
    | '/onboarding/wizard'
    | '/settings/download-clients'
    | '/settings/general'
    | '/settings/indexers'
    | '/settings/media-management'
    | '/settings/media-servers'
    | '/settings/notifications'
    | '/settings/plugins'
    | '/settings/profiles'
    | '/settings/scheduler'
    | '/settings/security'
    | '/settings/tags'
    | '/tv/$id'
    | '/activity/'
    | '/movies/'
    | '/onboarding/'
    | '/settings/'
    | '/tv/'
    | '/api/$version/calendar'
    | '/api/$version/customformat'
    | '/api/$version/health'
    | '/api/$version/qualityprofile'
    | '/api/$version/queue'
    | '/api/$version/rootfolder'
    | '/api/$version/tag'
    | '/api/system/health'
    | '/api/system/logs'
    | '/api/system/status'
    | '/api/system/tasks'
    | '/api/trpc/$'
    | '/api/$version/calendar/$id'
    | '/api/$version/customformat/$id'
    | '/api/$version/qualityprofile/$id'
    | '/api/$version/queue/$id'
    | '/api/$version/queue/details'
    | '/api/$version/queue/status'
    | '/api/$version/rootfolder/$id'
    | '/api/$version/system/status'
    | '/api/$version/tag/$id'
    | '/api/$version/tag/detail'
    | '/api/indexers/aggregate/$protocol'
    | '/api/queue/$id/blocklist'
    | '/api/queue/$id/remove'
    | '/api/queue/$id/retry'
    | '/api/$version/tag/detail/$id'
    | '/api/indexers/aggregate/$protocol/api'
    | '/api/system/backups/$id/download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/login'
    | '/system'
    | '/activity/history'
    | '/activity/queue'
    | '/activity/stats'
    | '/activity/users'
    | '/api/queue'
    | '/movies/$id'
    | '/onboarding/quickstart'
    | '/onboarding/wizard'
    | '/settings/download-clients'
    | '/settings/general'
    | '/settings/indexers'
    | '/settings/media-management'
    | '/settings/media-servers'
    | '/settings/notifications'
    | '/settings/plugins'
    | '/settings/profiles'
    | '/settings/scheduler'
    | '/settings/security'
    | '/settings/tags'
    | '/tv/$id'
    | '/activity'
    | '/movies'
    | '/onboarding'
    | '/settings'
    | '/tv'
    | '/api/$version/calendar'
    | '/api/$version/customformat'
    | '/api/$version/health'
    | '/api/$version/qualityprofile'
    | '/api/$version/queue'
    | '/api/$version/rootfolder'
    | '/api/$version/tag'
    | '/api/system/health'
    | '/api/system/logs'
    | '/api/system/status'
    | '/api/system/tasks'
    | '/api/trpc/$'
    | '/api/$version/calendar/$id'
    | '/api/$version/customformat/$id'
    | '/api/$version/qualityprofile/$id'
    | '/api/$version/queue/$id'
    | '/api/$version/queue/details'
    | '/api/$version/queue/status'
    | '/api/$version/rootfolder/$id'
    | '/api/$version/system/status'
    | '/api/$version/tag/$id'
    | '/api/$version/tag/detail'
    | '/api/indexers/aggregate/$protocol'
    | '/api/queue/$id/blocklist'
    | '/api/queue/$id/remove'
    | '/api/queue/$id/retry'
    | '/api/$version/tag/detail/$id'
    | '/api/indexers/aggregate/$protocol/api'
    | '/api/system/backups/$id/download'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/login'
    | '/system'
    | '/activity/history'
    | '/activity/queue'
    | '/activity/stats'
    | '/activity/users'
    | '/api/queue'
    | '/movies/$id'
    | '/onboarding/quickstart'
    | '/onboarding/wizard'
    | '/settings/download-clients'
    | '/settings/general'
    | '/settings/indexers'
    | '/settings/media-management'
    | '/settings/media-servers'
    | '/settings/notifications'
    | '/settings/plugins'
    | '/settings/profiles'
    | '/settings/scheduler'
    | '/settings/security'
    | '/settings/tags'
    | '/tv/$id'
    | '/activity/'
    | '/movies/'
    | '/onboarding/'
    | '/settings/'
    | '/tv/'
    | '/api/$version/calendar'
    | '/api/$version/customformat'
    | '/api/$version/health'
    | '/api/$version/qualityprofile'
    | '/api/$version/queue'
    | '/api/$version/rootfolder'
    | '/api/$version/tag'
    | '/api/system/health'
    | '/api/system/logs'
    | '/api/system/status'
    | '/api/system/tasks'
    | '/api/trpc/$'
    | '/api/$version/calendar/$id'
    | '/api/$version/customformat/$id'
    | '/api/$version/qualityprofile/$id'
    | '/api/$version/queue/$id'
    | '/api/$version/queue/details'
    | '/api/$version/queue/status'
    | '/api/$version/rootfolder/$id'
    | '/api/$version/system/status'
    | '/api/$version/tag/$id'
    | '/api/$version/tag/detail'
    | '/api/indexers/aggregate/$protocol'
    | '/api/queue/$id/blocklist'
    | '/api/queue/$id/remove'
    | '/api/queue/$id/retry'
    | '/api/$version/tag/detail/$id'
    | '/api/indexers/aggregate/$protocol/api'
    | '/api/system/backups/$id/download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  LoginRoute: typeof LoginRoute
  SystemRoute: typeof SystemRoute
  ActivityHistoryRoute: typeof ActivityHistoryRoute
  ActivityQueueRoute: typeof ActivityQueueRoute
  ActivityStatsRoute: typeof ActivityStatsRoute
  ActivityUsersRoute: typeof ActivityUsersRoute
  ApiQueueRoute: typeof ApiQueueRouteWithChildren
  MoviesIdRoute: typeof MoviesIdRoute
  OnboardingQuickstartRoute: typeof OnboardingQuickstartRoute
  OnboardingWizardRoute: typeof OnboardingWizardRoute
  SettingsDownloadClientsRoute: typeof SettingsDownloadClientsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsIndexersRoute: typeof SettingsIndexersRoute
  SettingsMediaManagementRoute: typeof SettingsMediaManagementRoute
  SettingsMediaServersRoute: typeof SettingsMediaServersRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPluginsRoute: typeof SettingsPluginsRoute
  SettingsProfilesRoute: typeof SettingsProfilesRoute
  SettingsSchedulerRoute: typeof SettingsSchedulerRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsTagsRoute: typeof SettingsTagsRoute
  TvIdRoute: typeof TvIdRoute
  ActivityIndexRoute: typeof ActivityIndexRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TvIndexRoute: typeof TvIndexRoute
  ApiVersionCalendarRoute: typeof ApiVersionCalendarRouteWithChildren
  ApiVersionCustomformatRoute: typeof ApiVersionCustomformatRouteWithChildren
  ApiVersionHealthRoute: typeof ApiVersionHealthRoute
  ApiVersionQualityprofileRoute: typeof ApiVersionQualityprofileRouteWithChildren
  ApiVersionQueueRoute: typeof ApiVersionQueueRouteWithChildren
  ApiVersionRootfolderRoute: typeof ApiVersionRootfolderRouteWithChildren
  ApiVersionTagRoute: typeof ApiVersionTagRouteWithChildren
  ApiSystemHealthRoute: typeof ApiSystemHealthRoute
  ApiSystemLogsRoute: typeof ApiSystemLogsRoute
  ApiSystemStatusRoute: typeof ApiSystemStatusRoute
  ApiSystemTasksRoute: typeof ApiSystemTasksRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiVersionSystemStatusRoute: typeof ApiVersionSystemStatusRoute
  ApiIndexersAggregateProtocolRoute: typeof ApiIndexersAggregateProtocolRouteWithChildren
  ApiSystemBackupsIdDownloadRoute: typeof ApiSystemBackupsIdDownloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/': {
      id: '/tv/'
      path: '/tv'
      fullPath: '/tv/'
      preLoaderRoute: typeof TvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/': {
      id: '/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof ActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$id': {
      id: '/tv/$id'
      path: '/tv/$id'
      fullPath: '/tv/$id'
      preLoaderRoute: typeof TvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tags': {
      id: '/settings/tags'
      path: '/settings/tags'
      fullPath: '/settings/tags'
      preLoaderRoute: typeof SettingsTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/scheduler': {
      id: '/settings/scheduler'
      path: '/settings/scheduler'
      fullPath: '/settings/scheduler'
      preLoaderRoute: typeof SettingsSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profiles': {
      id: '/settings/profiles'
      path: '/settings/profiles'
      fullPath: '/settings/profiles'
      preLoaderRoute: typeof SettingsProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/plugins': {
      id: '/settings/plugins'
      path: '/settings/plugins'
      fullPath: '/settings/plugins'
      preLoaderRoute: typeof SettingsPluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/media-servers': {
      id: '/settings/media-servers'
      path: '/settings/media-servers'
      fullPath: '/settings/media-servers'
      preLoaderRoute: typeof SettingsMediaServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/media-management': {
      id: '/settings/media-management'
      path: '/settings/media-management'
      fullPath: '/settings/media-management'
      preLoaderRoute: typeof SettingsMediaManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/indexers': {
      id: '/settings/indexers'
      path: '/settings/indexers'
      fullPath: '/settings/indexers'
      preLoaderRoute: typeof SettingsIndexersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/download-clients': {
      id: '/settings/download-clients'
      path: '/settings/download-clients'
      fullPath: '/settings/download-clients'
      preLoaderRoute: typeof SettingsDownloadClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/wizard': {
      id: '/onboarding/wizard'
      path: '/onboarding/wizard'
      fullPath: '/onboarding/wizard'
      preLoaderRoute: typeof OnboardingWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/quickstart': {
      id: '/onboarding/quickstart'
      path: '/onboarding/quickstart'
      fullPath: '/onboarding/quickstart'
      preLoaderRoute: typeof OnboardingQuickstartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$id': {
      id: '/movies/$id'
      path: '/movies/$id'
      fullPath: '/movies/$id'
      preLoaderRoute: typeof MoviesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queue': {
      id: '/api/queue'
      path: '/api/queue'
      fullPath: '/api/queue'
      preLoaderRoute: typeof ApiQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/users': {
      id: '/activity/users'
      path: '/activity/users'
      fullPath: '/activity/users'
      preLoaderRoute: typeof ActivityUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/stats': {
      id: '/activity/stats'
      path: '/activity/stats'
      fullPath: '/activity/stats'
      preLoaderRoute: typeof ActivityStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/queue': {
      id: '/activity/queue'
      path: '/activity/queue'
      fullPath: '/activity/queue'
      preLoaderRoute: typeof ActivityQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/history': {
      id: '/activity/history'
      path: '/activity/history'
      fullPath: '/activity/history'
      preLoaderRoute: typeof ActivityHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/tasks': {
      id: '/api/system/tasks'
      path: '/api/system/tasks'
      fullPath: '/api/system/tasks'
      preLoaderRoute: typeof ApiSystemTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/status': {
      id: '/api/system/status'
      path: '/api/system/status'
      fullPath: '/api/system/status'
      preLoaderRoute: typeof ApiSystemStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/logs': {
      id: '/api/system/logs'
      path: '/api/system/logs'
      fullPath: '/api/system/logs'
      preLoaderRoute: typeof ApiSystemLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/health': {
      id: '/api/system/health'
      path: '/api/system/health'
      fullPath: '/api/system/health'
      preLoaderRoute: typeof ApiSystemHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$version/tag': {
      id: '/api/$version/tag'
      path: '/api/$version/tag'
      fullPath: '/api/$version/tag'
      preLoaderRoute: typeof ApiVersionTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$version/rootfolder': {
      id: '/api/$version/rootfolder'
      path: '/api/$version/rootfolder'
      fullPath: '/api/$version/rootfolder'
      preLoaderRoute: typeof ApiVersionRootfolderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$version/queue': {
      id: '/api/$version/queue'
      path: '/api/$version/queue'
      fullPath: '/api/$version/queue'
      preLoaderRoute: typeof ApiVersionQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$version/qualityprofile': {
      id: '/api/$version/qualityprofile'
      path: '/api/$version/qualityprofile'
      fullPath: '/api/$version/qualityprofile'
      preLoaderRoute: typeof ApiVersionQualityprofileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$version/health': {
      id: '/api/$version/health'
      path: '/api/$version/health'
      fullPath: '/api/$version/health'
      preLoaderRoute: typeof ApiVersionHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$version/customformat': {
      id: '/api/$version/customformat'
      path: '/api/$version/customformat'
      fullPath: '/api/$version/customformat'
      preLoaderRoute: typeof ApiVersionCustomformatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$version/calendar': {
      id: '/api/$version/calendar'
      path: '/api/$version/calendar'
      fullPath: '/api/$version/calendar'
      preLoaderRoute: typeof ApiVersionCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queue/$id/retry': {
      id: '/api/queue/$id/retry'
      path: '/$id/retry'
      fullPath: '/api/queue/$id/retry'
      preLoaderRoute: typeof ApiQueueIdRetryRouteImport
      parentRoute: typeof ApiQueueRoute
    }
    '/api/queue/$id/remove': {
      id: '/api/queue/$id/remove'
      path: '/$id/remove'
      fullPath: '/api/queue/$id/remove'
      preLoaderRoute: typeof ApiQueueIdRemoveRouteImport
      parentRoute: typeof ApiQueueRoute
    }
    '/api/queue/$id/blocklist': {
      id: '/api/queue/$id/blocklist'
      path: '/$id/blocklist'
      fullPath: '/api/queue/$id/blocklist'
      preLoaderRoute: typeof ApiQueueIdBlocklistRouteImport
      parentRoute: typeof ApiQueueRoute
    }
    '/api/indexers/aggregate/$protocol': {
      id: '/api/indexers/aggregate/$protocol'
      path: '/api/indexers/aggregate/$protocol'
      fullPath: '/api/indexers/aggregate/$protocol'
      preLoaderRoute: typeof ApiIndexersAggregateProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$version/tag/detail': {
      id: '/api/$version/tag/detail'
      path: '/detail'
      fullPath: '/api/$version/tag/detail'
      preLoaderRoute: typeof ApiVersionTagDetailRouteImport
      parentRoute: typeof ApiVersionTagRoute
    }
    '/api/$version/tag/$id': {
      id: '/api/$version/tag/$id'
      path: '/$id'
      fullPath: '/api/$version/tag/$id'
      preLoaderRoute: typeof ApiVersionTagIdRouteImport
      parentRoute: typeof ApiVersionTagRoute
    }
    '/api/$version/system/status': {
      id: '/api/$version/system/status'
      path: '/api/$version/system/status'
      fullPath: '/api/$version/system/status'
      preLoaderRoute: typeof ApiVersionSystemStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$version/rootfolder/$id': {
      id: '/api/$version/rootfolder/$id'
      path: '/$id'
      fullPath: '/api/$version/rootfolder/$id'
      preLoaderRoute: typeof ApiVersionRootfolderIdRouteImport
      parentRoute: typeof ApiVersionRootfolderRoute
    }
    '/api/$version/queue/status': {
      id: '/api/$version/queue/status'
      path: '/status'
      fullPath: '/api/$version/queue/status'
      preLoaderRoute: typeof ApiVersionQueueStatusRouteImport
      parentRoute: typeof ApiVersionQueueRoute
    }
    '/api/$version/queue/details': {
      id: '/api/$version/queue/details'
      path: '/details'
      fullPath: '/api/$version/queue/details'
      preLoaderRoute: typeof ApiVersionQueueDetailsRouteImport
      parentRoute: typeof ApiVersionQueueRoute
    }
    '/api/$version/queue/$id': {
      id: '/api/$version/queue/$id'
      path: '/$id'
      fullPath: '/api/$version/queue/$id'
      preLoaderRoute: typeof ApiVersionQueueIdRouteImport
      parentRoute: typeof ApiVersionQueueRoute
    }
    '/api/$version/qualityprofile/$id': {
      id: '/api/$version/qualityprofile/$id'
      path: '/$id'
      fullPath: '/api/$version/qualityprofile/$id'
      preLoaderRoute: typeof ApiVersionQualityprofileIdRouteImport
      parentRoute: typeof ApiVersionQualityprofileRoute
    }
    '/api/$version/customformat/$id': {
      id: '/api/$version/customformat/$id'
      path: '/$id'
      fullPath: '/api/$version/customformat/$id'
      preLoaderRoute: typeof ApiVersionCustomformatIdRouteImport
      parentRoute: typeof ApiVersionCustomformatRoute
    }
    '/api/$version/calendar/$id': {
      id: '/api/$version/calendar/$id'
      path: '/$id'
      fullPath: '/api/$version/calendar/$id'
      preLoaderRoute: typeof ApiVersionCalendarIdRouteImport
      parentRoute: typeof ApiVersionCalendarRoute
    }
    '/api/system/backups/$id/download': {
      id: '/api/system/backups/$id/download'
      path: '/api/system/backups/$id/download'
      fullPath: '/api/system/backups/$id/download'
      preLoaderRoute: typeof ApiSystemBackupsIdDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/indexers/aggregate/$protocol/api': {
      id: '/api/indexers/aggregate/$protocol/api'
      path: '/api'
      fullPath: '/api/indexers/aggregate/$protocol/api'
      preLoaderRoute: typeof ApiIndexersAggregateProtocolApiRouteImport
      parentRoute: typeof ApiIndexersAggregateProtocolRoute
    }
    '/api/$version/tag/detail/$id': {
      id: '/api/$version/tag/detail/$id'
      path: '/$id'
      fullPath: '/api/$version/tag/detail/$id'
      preLoaderRoute: typeof ApiVersionTagDetailIdRouteImport
      parentRoute: typeof ApiVersionTagDetailRoute
    }
  }
}

interface ApiQueueRouteChildren {
  ApiQueueIdBlocklistRoute: typeof ApiQueueIdBlocklistRoute
  ApiQueueIdRemoveRoute: typeof ApiQueueIdRemoveRoute
  ApiQueueIdRetryRoute: typeof ApiQueueIdRetryRoute
}

const ApiQueueRouteChildren: ApiQueueRouteChildren = {
  ApiQueueIdBlocklistRoute: ApiQueueIdBlocklistRoute,
  ApiQueueIdRemoveRoute: ApiQueueIdRemoveRoute,
  ApiQueueIdRetryRoute: ApiQueueIdRetryRoute,
}

const ApiQueueRouteWithChildren = ApiQueueRoute._addFileChildren(
  ApiQueueRouteChildren,
)

interface ApiVersionCalendarRouteChildren {
  ApiVersionCalendarIdRoute: typeof ApiVersionCalendarIdRoute
}

const ApiVersionCalendarRouteChildren: ApiVersionCalendarRouteChildren = {
  ApiVersionCalendarIdRoute: ApiVersionCalendarIdRoute,
}

const ApiVersionCalendarRouteWithChildren =
  ApiVersionCalendarRoute._addFileChildren(ApiVersionCalendarRouteChildren)

interface ApiVersionCustomformatRouteChildren {
  ApiVersionCustomformatIdRoute: typeof ApiVersionCustomformatIdRoute
}

const ApiVersionCustomformatRouteChildren: ApiVersionCustomformatRouteChildren =
  {
    ApiVersionCustomformatIdRoute: ApiVersionCustomformatIdRoute,
  }

const ApiVersionCustomformatRouteWithChildren =
  ApiVersionCustomformatRoute._addFileChildren(
    ApiVersionCustomformatRouteChildren,
  )

interface ApiVersionQualityprofileRouteChildren {
  ApiVersionQualityprofileIdRoute: typeof ApiVersionQualityprofileIdRoute
}

const ApiVersionQualityprofileRouteChildren: ApiVersionQualityprofileRouteChildren =
  {
    ApiVersionQualityprofileIdRoute: ApiVersionQualityprofileIdRoute,
  }

const ApiVersionQualityprofileRouteWithChildren =
  ApiVersionQualityprofileRoute._addFileChildren(
    ApiVersionQualityprofileRouteChildren,
  )

interface ApiVersionQueueRouteChildren {
  ApiVersionQueueIdRoute: typeof ApiVersionQueueIdRoute
  ApiVersionQueueDetailsRoute: typeof ApiVersionQueueDetailsRoute
  ApiVersionQueueStatusRoute: typeof ApiVersionQueueStatusRoute
}

const ApiVersionQueueRouteChildren: ApiVersionQueueRouteChildren = {
  ApiVersionQueueIdRoute: ApiVersionQueueIdRoute,
  ApiVersionQueueDetailsRoute: ApiVersionQueueDetailsRoute,
  ApiVersionQueueStatusRoute: ApiVersionQueueStatusRoute,
}

const ApiVersionQueueRouteWithChildren = ApiVersionQueueRoute._addFileChildren(
  ApiVersionQueueRouteChildren,
)

interface ApiVersionRootfolderRouteChildren {
  ApiVersionRootfolderIdRoute: typeof ApiVersionRootfolderIdRoute
}

const ApiVersionRootfolderRouteChildren: ApiVersionRootfolderRouteChildren = {
  ApiVersionRootfolderIdRoute: ApiVersionRootfolderIdRoute,
}

const ApiVersionRootfolderRouteWithChildren =
  ApiVersionRootfolderRoute._addFileChildren(ApiVersionRootfolderRouteChildren)

interface ApiVersionTagDetailRouteChildren {
  ApiVersionTagDetailIdRoute: typeof ApiVersionTagDetailIdRoute
}

const ApiVersionTagDetailRouteChildren: ApiVersionTagDetailRouteChildren = {
  ApiVersionTagDetailIdRoute: ApiVersionTagDetailIdRoute,
}

const ApiVersionTagDetailRouteWithChildren =
  ApiVersionTagDetailRoute._addFileChildren(ApiVersionTagDetailRouteChildren)

interface ApiVersionTagRouteChildren {
  ApiVersionTagIdRoute: typeof ApiVersionTagIdRoute
  ApiVersionTagDetailRoute: typeof ApiVersionTagDetailRouteWithChildren
}

const ApiVersionTagRouteChildren: ApiVersionTagRouteChildren = {
  ApiVersionTagIdRoute: ApiVersionTagIdRoute,
  ApiVersionTagDetailRoute: ApiVersionTagDetailRouteWithChildren,
}

const ApiVersionTagRouteWithChildren = ApiVersionTagRoute._addFileChildren(
  ApiVersionTagRouteChildren,
)

interface ApiIndexersAggregateProtocolRouteChildren {
  ApiIndexersAggregateProtocolApiRoute: typeof ApiIndexersAggregateProtocolApiRoute
}

const ApiIndexersAggregateProtocolRouteChildren: ApiIndexersAggregateProtocolRouteChildren =
  {
    ApiIndexersAggregateProtocolApiRoute: ApiIndexersAggregateProtocolApiRoute,
  }

const ApiIndexersAggregateProtocolRouteWithChildren =
  ApiIndexersAggregateProtocolRoute._addFileChildren(
    ApiIndexersAggregateProtocolRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  LoginRoute: LoginRoute,
  SystemRoute: SystemRoute,
  ActivityHistoryRoute: ActivityHistoryRoute,
  ActivityQueueRoute: ActivityQueueRoute,
  ActivityStatsRoute: ActivityStatsRoute,
  ActivityUsersRoute: ActivityUsersRoute,
  ApiQueueRoute: ApiQueueRouteWithChildren,
  MoviesIdRoute: MoviesIdRoute,
  OnboardingQuickstartRoute: OnboardingQuickstartRoute,
  OnboardingWizardRoute: OnboardingWizardRoute,
  SettingsDownloadClientsRoute: SettingsDownloadClientsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsIndexersRoute: SettingsIndexersRoute,
  SettingsMediaManagementRoute: SettingsMediaManagementRoute,
  SettingsMediaServersRoute: SettingsMediaServersRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPluginsRoute: SettingsPluginsRoute,
  SettingsProfilesRoute: SettingsProfilesRoute,
  SettingsSchedulerRoute: SettingsSchedulerRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsTagsRoute: SettingsTagsRoute,
  TvIdRoute: TvIdRoute,
  ActivityIndexRoute: ActivityIndexRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TvIndexRoute: TvIndexRoute,
  ApiVersionCalendarRoute: ApiVersionCalendarRouteWithChildren,
  ApiVersionCustomformatRoute: ApiVersionCustomformatRouteWithChildren,
  ApiVersionHealthRoute: ApiVersionHealthRoute,
  ApiVersionQualityprofileRoute: ApiVersionQualityprofileRouteWithChildren,
  ApiVersionQueueRoute: ApiVersionQueueRouteWithChildren,
  ApiVersionRootfolderRoute: ApiVersionRootfolderRouteWithChildren,
  ApiVersionTagRoute: ApiVersionTagRouteWithChildren,
  ApiSystemHealthRoute: ApiSystemHealthRoute,
  ApiSystemLogsRoute: ApiSystemLogsRoute,
  ApiSystemStatusRoute: ApiSystemStatusRoute,
  ApiSystemTasksRoute: ApiSystemTasksRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiVersionSystemStatusRoute: ApiVersionSystemStatusRoute,
  ApiIndexersAggregateProtocolRoute:
    ApiIndexersAggregateProtocolRouteWithChildren,
  ApiSystemBackupsIdDownloadRoute: ApiSystemBackupsIdDownloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
