/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/system'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvIndexRouteImport } from './routes/tv/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as MoviesIndexRouteImport } from './routes/movies/index'
import { Route as ActivityIndexRouteImport } from './routes/activity/index'
import { Route as TvIdRouteImport } from './routes/tv/$id'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsSchedulerRouteImport } from './routes/settings/scheduler'
import { Route as SettingsProfilesRouteImport } from './routes/settings/profiles'
import { Route as SettingsPluginsRouteImport } from './routes/settings/plugins'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsMediaServersRouteImport } from './routes/settings/media-servers'
import { Route as SettingsMediaManagementRouteImport } from './routes/settings/media-management'
import { Route as SettingsIndexersRouteImport } from './routes/settings/indexers'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'
import { Route as SettingsDownloadClientsRouteImport } from './routes/settings/download-clients'
import { Route as OnboardingWizardRouteImport } from './routes/onboarding/wizard'
import { Route as OnboardingQuickstartRouteImport } from './routes/onboarding/quickstart'
import { Route as MoviesIdRouteImport } from './routes/movies/$id'
import { Route as ApiQueueRouteImport } from './routes/api.queue'
import { Route as ActivityUsersRouteImport } from './routes/activity/users'
import { Route as ActivityStatsRouteImport } from './routes/activity/stats'
import { Route as ActivityQueueRouteImport } from './routes/activity/queue'
import { Route as ActivityHistoryRouteImport } from './routes/activity/history'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiSystemTasksRouteImport } from './routes/api.system.tasks'
import { Route as ApiSystemStatusRouteImport } from './routes/api.system.status'
import { Route as ApiSystemLogsRouteImport } from './routes/api.system.logs'
import { Route as ApiSystemHealthRouteImport } from './routes/api.system.health'
import { Route as ApiQueueIdRetryRouteImport } from './routes/api.queue.$id.retry'
import { Route as ApiQueueIdRemoveRouteImport } from './routes/api.queue.$id.remove'
import { Route as ApiQueueIdBlocklistRouteImport } from './routes/api.queue.$id.blocklist'
import { Route as ApiIndexersAggregateProtocolRouteImport } from './routes/api.indexers.aggregate.$protocol'

const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIndexRoute = TvIndexRouteImport.update({
  id: '/tv/',
  path: '/tv/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIdRoute = TvIdRouteImport.update({
  id: '/tv/$id',
  path: '/tv/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSchedulerRoute = SettingsSchedulerRouteImport.update({
  id: '/settings/scheduler',
  path: '/settings/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfilesRoute = SettingsProfilesRouteImport.update({
  id: '/settings/profiles',
  path: '/settings/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPluginsRoute = SettingsPluginsRouteImport.update({
  id: '/settings/plugins',
  path: '/settings/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMediaServersRoute = SettingsMediaServersRouteImport.update({
  id: '/settings/media-servers',
  path: '/settings/media-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMediaManagementRoute = SettingsMediaManagementRouteImport.update({
  id: '/settings/media-management',
  path: '/settings/media-management',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexersRoute = SettingsIndexersRouteImport.update({
  id: '/settings/indexers',
  path: '/settings/indexers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDownloadClientsRoute = SettingsDownloadClientsRouteImport.update({
  id: '/settings/download-clients',
  path: '/settings/download-clients',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWizardRoute = OnboardingWizardRouteImport.update({
  id: '/onboarding/wizard',
  path: '/onboarding/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingQuickstartRoute = OnboardingQuickstartRouteImport.update({
  id: '/onboarding/quickstart',
  path: '/onboarding/quickstart',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIdRoute = MoviesIdRouteImport.update({
  id: '/movies/$id',
  path: '/movies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueueRoute = ApiQueueRouteImport.update({
  id: '/api/queue',
  path: '/api/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityUsersRoute = ActivityUsersRouteImport.update({
  id: '/activity/users',
  path: '/activity/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityStatsRoute = ActivityStatsRouteImport.update({
  id: '/activity/stats',
  path: '/activity/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityQueueRoute = ActivityQueueRouteImport.update({
  id: '/activity/queue',
  path: '/activity/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityHistoryRoute = ActivityHistoryRouteImport.update({
  id: '/activity/history',
  path: '/activity/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemTasksRoute = ApiSystemTasksRouteImport.update({
  id: '/api/system/tasks',
  path: '/api/system/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemStatusRoute = ApiSystemStatusRouteImport.update({
  id: '/api/system/status',
  path: '/api/system/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemLogsRoute = ApiSystemLogsRouteImport.update({
  id: '/api/system/logs',
  path: '/api/system/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemHealthRoute = ApiSystemHealthRouteImport.update({
  id: '/api/system/health',
  path: '/api/system/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueueIdRetryRoute = ApiQueueIdRetryRouteImport.update({
  id: '/$id/retry',
  path: '/$id/retry',
  getParentRoute: () => ApiQueueRoute,
} as any)
const ApiQueueIdRemoveRoute = ApiQueueIdRemoveRouteImport.update({
  id: '/$id/remove',
  path: '/$id/remove',
  getParentRoute: () => ApiQueueRoute,
} as any)
const ApiQueueIdBlocklistRoute = ApiQueueIdBlocklistRouteImport.update({
  id: '/$id/blocklist',
  path: '/$id/blocklist',
  getParentRoute: () => ApiQueueRoute,
} as any)
const ApiIndexersAggregateProtocolRoute =
  ApiIndexersAggregateProtocolRouteImport.update({
    id: '/api/indexers/aggregate/$protocol',
    path: '/api/indexers/aggregate/$protocol',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/system': typeof SystemRoute
  '/activity/history': typeof ActivityHistoryRoute
  '/activity/queue': typeof ActivityQueueRoute
  '/activity/stats': typeof ActivityStatsRoute
  '/activity/users': typeof ActivityUsersRoute
  '/api/queue': typeof ApiQueueRouteWithChildren
  '/movies/$id': typeof MoviesIdRoute
  '/onboarding/quickstart': typeof OnboardingQuickstartRoute
  '/onboarding/wizard': typeof OnboardingWizardRoute
  '/settings/download-clients': typeof SettingsDownloadClientsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/indexers': typeof SettingsIndexersRoute
  '/settings/media-management': typeof SettingsMediaManagementRoute
  '/settings/media-servers': typeof SettingsMediaServersRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/settings/profiles': typeof SettingsProfilesRoute
  '/settings/scheduler': typeof SettingsSchedulerRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/tv/$id': typeof TvIdRoute
  '/activity/': typeof ActivityIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tv/': typeof TvIndexRoute
  '/api/system/health': typeof ApiSystemHealthRoute
  '/api/system/logs': typeof ApiSystemLogsRoute
  '/api/system/status': typeof ApiSystemStatusRoute
  '/api/system/tasks': typeof ApiSystemTasksRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/indexers/aggregate/$protocol': typeof ApiIndexersAggregateProtocolRoute
  '/api/queue/$id/blocklist': typeof ApiQueueIdBlocklistRoute
  '/api/queue/$id/remove': typeof ApiQueueIdRemoveRoute
  '/api/queue/$id/retry': typeof ApiQueueIdRetryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/system': typeof SystemRoute
  '/activity/history': typeof ActivityHistoryRoute
  '/activity/queue': typeof ActivityQueueRoute
  '/activity/stats': typeof ActivityStatsRoute
  '/activity/users': typeof ActivityUsersRoute
  '/api/queue': typeof ApiQueueRouteWithChildren
  '/movies/$id': typeof MoviesIdRoute
  '/onboarding/quickstart': typeof OnboardingQuickstartRoute
  '/onboarding/wizard': typeof OnboardingWizardRoute
  '/settings/download-clients': typeof SettingsDownloadClientsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/indexers': typeof SettingsIndexersRoute
  '/settings/media-management': typeof SettingsMediaManagementRoute
  '/settings/media-servers': typeof SettingsMediaServersRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/settings/profiles': typeof SettingsProfilesRoute
  '/settings/scheduler': typeof SettingsSchedulerRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/tv/$id': typeof TvIdRoute
  '/activity': typeof ActivityIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tv': typeof TvIndexRoute
  '/api/system/health': typeof ApiSystemHealthRoute
  '/api/system/logs': typeof ApiSystemLogsRoute
  '/api/system/status': typeof ApiSystemStatusRoute
  '/api/system/tasks': typeof ApiSystemTasksRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/indexers/aggregate/$protocol': typeof ApiIndexersAggregateProtocolRoute
  '/api/queue/$id/blocklist': typeof ApiQueueIdBlocklistRoute
  '/api/queue/$id/remove': typeof ApiQueueIdRemoveRoute
  '/api/queue/$id/retry': typeof ApiQueueIdRetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/system': typeof SystemRoute
  '/activity/history': typeof ActivityHistoryRoute
  '/activity/queue': typeof ActivityQueueRoute
  '/activity/stats': typeof ActivityStatsRoute
  '/activity/users': typeof ActivityUsersRoute
  '/api/queue': typeof ApiQueueRouteWithChildren
  '/movies/$id': typeof MoviesIdRoute
  '/onboarding/quickstart': typeof OnboardingQuickstartRoute
  '/onboarding/wizard': typeof OnboardingWizardRoute
  '/settings/download-clients': typeof SettingsDownloadClientsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/indexers': typeof SettingsIndexersRoute
  '/settings/media-management': typeof SettingsMediaManagementRoute
  '/settings/media-servers': typeof SettingsMediaServersRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/settings/profiles': typeof SettingsProfilesRoute
  '/settings/scheduler': typeof SettingsSchedulerRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/tv/$id': typeof TvIdRoute
  '/activity/': typeof ActivityIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tv/': typeof TvIndexRoute
  '/api/system/health': typeof ApiSystemHealthRoute
  '/api/system/logs': typeof ApiSystemLogsRoute
  '/api/system/status': typeof ApiSystemStatusRoute
  '/api/system/tasks': typeof ApiSystemTasksRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/indexers/aggregate/$protocol': typeof ApiIndexersAggregateProtocolRoute
  '/api/queue/$id/blocklist': typeof ApiQueueIdBlocklistRoute
  '/api/queue/$id/remove': typeof ApiQueueIdRemoveRoute
  '/api/queue/$id/retry': typeof ApiQueueIdRetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/login'
    | '/system'
    | '/activity/history'
    | '/activity/queue'
    | '/activity/stats'
    | '/activity/users'
    | '/api/queue'
    | '/movies/$id'
    | '/onboarding/quickstart'
    | '/onboarding/wizard'
    | '/settings/download-clients'
    | '/settings/general'
    | '/settings/indexers'
    | '/settings/media-management'
    | '/settings/media-servers'
    | '/settings/notifications'
    | '/settings/plugins'
    | '/settings/profiles'
    | '/settings/scheduler'
    | '/settings/security'
    | '/tv/$id'
    | '/activity/'
    | '/movies/'
    | '/onboarding/'
    | '/settings/'
    | '/tv/'
    | '/api/system/health'
    | '/api/system/logs'
    | '/api/system/status'
    | '/api/system/tasks'
    | '/api/trpc/$'
    | '/api/indexers/aggregate/$protocol'
    | '/api/queue/$id/blocklist'
    | '/api/queue/$id/remove'
    | '/api/queue/$id/retry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/login'
    | '/system'
    | '/activity/history'
    | '/activity/queue'
    | '/activity/stats'
    | '/activity/users'
    | '/api/queue'
    | '/movies/$id'
    | '/onboarding/quickstart'
    | '/onboarding/wizard'
    | '/settings/download-clients'
    | '/settings/general'
    | '/settings/indexers'
    | '/settings/media-management'
    | '/settings/media-servers'
    | '/settings/notifications'
    | '/settings/plugins'
    | '/settings/profiles'
    | '/settings/scheduler'
    | '/settings/security'
    | '/tv/$id'
    | '/activity'
    | '/movies'
    | '/onboarding'
    | '/settings'
    | '/tv'
    | '/api/system/health'
    | '/api/system/logs'
    | '/api/system/status'
    | '/api/system/tasks'
    | '/api/trpc/$'
    | '/api/indexers/aggregate/$protocol'
    | '/api/queue/$id/blocklist'
    | '/api/queue/$id/remove'
    | '/api/queue/$id/retry'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/login'
    | '/system'
    | '/activity/history'
    | '/activity/queue'
    | '/activity/stats'
    | '/activity/users'
    | '/api/queue'
    | '/movies/$id'
    | '/onboarding/quickstart'
    | '/onboarding/wizard'
    | '/settings/download-clients'
    | '/settings/general'
    | '/settings/indexers'
    | '/settings/media-management'
    | '/settings/media-servers'
    | '/settings/notifications'
    | '/settings/plugins'
    | '/settings/profiles'
    | '/settings/scheduler'
    | '/settings/security'
    | '/tv/$id'
    | '/activity/'
    | '/movies/'
    | '/onboarding/'
    | '/settings/'
    | '/tv/'
    | '/api/system/health'
    | '/api/system/logs'
    | '/api/system/status'
    | '/api/system/tasks'
    | '/api/trpc/$'
    | '/api/indexers/aggregate/$protocol'
    | '/api/queue/$id/blocklist'
    | '/api/queue/$id/remove'
    | '/api/queue/$id/retry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  LoginRoute: typeof LoginRoute
  SystemRoute: typeof SystemRoute
  ActivityHistoryRoute: typeof ActivityHistoryRoute
  ActivityQueueRoute: typeof ActivityQueueRoute
  ActivityStatsRoute: typeof ActivityStatsRoute
  ActivityUsersRoute: typeof ActivityUsersRoute
  ApiQueueRoute: typeof ApiQueueRouteWithChildren
  MoviesIdRoute: typeof MoviesIdRoute
  OnboardingQuickstartRoute: typeof OnboardingQuickstartRoute
  OnboardingWizardRoute: typeof OnboardingWizardRoute
  SettingsDownloadClientsRoute: typeof SettingsDownloadClientsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsIndexersRoute: typeof SettingsIndexersRoute
  SettingsMediaManagementRoute: typeof SettingsMediaManagementRoute
  SettingsMediaServersRoute: typeof SettingsMediaServersRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPluginsRoute: typeof SettingsPluginsRoute
  SettingsProfilesRoute: typeof SettingsProfilesRoute
  SettingsSchedulerRoute: typeof SettingsSchedulerRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  TvIdRoute: typeof TvIdRoute
  ActivityIndexRoute: typeof ActivityIndexRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TvIndexRoute: typeof TvIndexRoute
  ApiSystemHealthRoute: typeof ApiSystemHealthRoute
  ApiSystemLogsRoute: typeof ApiSystemLogsRoute
  ApiSystemStatusRoute: typeof ApiSystemStatusRoute
  ApiSystemTasksRoute: typeof ApiSystemTasksRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiIndexersAggregateProtocolRoute: typeof ApiIndexersAggregateProtocolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/': {
      id: '/tv/'
      path: '/tv'
      fullPath: '/tv/'
      preLoaderRoute: typeof TvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/': {
      id: '/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof ActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$id': {
      id: '/tv/$id'
      path: '/tv/$id'
      fullPath: '/tv/$id'
      preLoaderRoute: typeof TvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/scheduler': {
      id: '/settings/scheduler'
      path: '/settings/scheduler'
      fullPath: '/settings/scheduler'
      preLoaderRoute: typeof SettingsSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profiles': {
      id: '/settings/profiles'
      path: '/settings/profiles'
      fullPath: '/settings/profiles'
      preLoaderRoute: typeof SettingsProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/plugins': {
      id: '/settings/plugins'
      path: '/settings/plugins'
      fullPath: '/settings/plugins'
      preLoaderRoute: typeof SettingsPluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/media-servers': {
      id: '/settings/media-servers'
      path: '/settings/media-servers'
      fullPath: '/settings/media-servers'
      preLoaderRoute: typeof SettingsMediaServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/media-management': {
      id: '/settings/media-management'
      path: '/settings/media-management'
      fullPath: '/settings/media-management'
      preLoaderRoute: typeof SettingsMediaManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/indexers': {
      id: '/settings/indexers'
      path: '/settings/indexers'
      fullPath: '/settings/indexers'
      preLoaderRoute: typeof SettingsIndexersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/download-clients': {
      id: '/settings/download-clients'
      path: '/settings/download-clients'
      fullPath: '/settings/download-clients'
      preLoaderRoute: typeof SettingsDownloadClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/wizard': {
      id: '/onboarding/wizard'
      path: '/onboarding/wizard'
      fullPath: '/onboarding/wizard'
      preLoaderRoute: typeof OnboardingWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/quickstart': {
      id: '/onboarding/quickstart'
      path: '/onboarding/quickstart'
      fullPath: '/onboarding/quickstart'
      preLoaderRoute: typeof OnboardingQuickstartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$id': {
      id: '/movies/$id'
      path: '/movies/$id'
      fullPath: '/movies/$id'
      preLoaderRoute: typeof MoviesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queue': {
      id: '/api/queue'
      path: '/api/queue'
      fullPath: '/api/queue'
      preLoaderRoute: typeof ApiQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/users': {
      id: '/activity/users'
      path: '/activity/users'
      fullPath: '/activity/users'
      preLoaderRoute: typeof ActivityUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/stats': {
      id: '/activity/stats'
      path: '/activity/stats'
      fullPath: '/activity/stats'
      preLoaderRoute: typeof ActivityStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/queue': {
      id: '/activity/queue'
      path: '/activity/queue'
      fullPath: '/activity/queue'
      preLoaderRoute: typeof ActivityQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/history': {
      id: '/activity/history'
      path: '/activity/history'
      fullPath: '/activity/history'
      preLoaderRoute: typeof ActivityHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/tasks': {
      id: '/api/system/tasks'
      path: '/api/system/tasks'
      fullPath: '/api/system/tasks'
      preLoaderRoute: typeof ApiSystemTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/status': {
      id: '/api/system/status'
      path: '/api/system/status'
      fullPath: '/api/system/status'
      preLoaderRoute: typeof ApiSystemStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/logs': {
      id: '/api/system/logs'
      path: '/api/system/logs'
      fullPath: '/api/system/logs'
      preLoaderRoute: typeof ApiSystemLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/health': {
      id: '/api/system/health'
      path: '/api/system/health'
      fullPath: '/api/system/health'
      preLoaderRoute: typeof ApiSystemHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queue/$id/retry': {
      id: '/api/queue/$id/retry'
      path: '/$id/retry'
      fullPath: '/api/queue/$id/retry'
      preLoaderRoute: typeof ApiQueueIdRetryRouteImport
      parentRoute: typeof ApiQueueRoute
    }
    '/api/queue/$id/remove': {
      id: '/api/queue/$id/remove'
      path: '/$id/remove'
      fullPath: '/api/queue/$id/remove'
      preLoaderRoute: typeof ApiQueueIdRemoveRouteImport
      parentRoute: typeof ApiQueueRoute
    }
    '/api/queue/$id/blocklist': {
      id: '/api/queue/$id/blocklist'
      path: '/$id/blocklist'
      fullPath: '/api/queue/$id/blocklist'
      preLoaderRoute: typeof ApiQueueIdBlocklistRouteImport
      parentRoute: typeof ApiQueueRoute
    }
    '/api/indexers/aggregate/$protocol': {
      id: '/api/indexers/aggregate/$protocol'
      path: '/api/indexers/aggregate/$protocol'
      fullPath: '/api/indexers/aggregate/$protocol'
      preLoaderRoute: typeof ApiIndexersAggregateProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiQueueRouteChildren {
  ApiQueueIdBlocklistRoute: typeof ApiQueueIdBlocklistRoute
  ApiQueueIdRemoveRoute: typeof ApiQueueIdRemoveRoute
  ApiQueueIdRetryRoute: typeof ApiQueueIdRetryRoute
}

const ApiQueueRouteChildren: ApiQueueRouteChildren = {
  ApiQueueIdBlocklistRoute: ApiQueueIdBlocklistRoute,
  ApiQueueIdRemoveRoute: ApiQueueIdRemoveRoute,
  ApiQueueIdRetryRoute: ApiQueueIdRetryRoute,
}

const ApiQueueRouteWithChildren = ApiQueueRoute._addFileChildren(
  ApiQueueRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  LoginRoute: LoginRoute,
  SystemRoute: SystemRoute,
  ActivityHistoryRoute: ActivityHistoryRoute,
  ActivityQueueRoute: ActivityQueueRoute,
  ActivityStatsRoute: ActivityStatsRoute,
  ActivityUsersRoute: ActivityUsersRoute,
  ApiQueueRoute: ApiQueueRouteWithChildren,
  MoviesIdRoute: MoviesIdRoute,
  OnboardingQuickstartRoute: OnboardingQuickstartRoute,
  OnboardingWizardRoute: OnboardingWizardRoute,
  SettingsDownloadClientsRoute: SettingsDownloadClientsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsIndexersRoute: SettingsIndexersRoute,
  SettingsMediaManagementRoute: SettingsMediaManagementRoute,
  SettingsMediaServersRoute: SettingsMediaServersRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPluginsRoute: SettingsPluginsRoute,
  SettingsProfilesRoute: SettingsProfilesRoute,
  SettingsSchedulerRoute: SettingsSchedulerRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  TvIdRoute: TvIdRoute,
  ActivityIndexRoute: ActivityIndexRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TvIndexRoute: TvIndexRoute,
  ApiSystemHealthRoute: ApiSystemHealthRoute,
  ApiSystemLogsRoute: ApiSystemLogsRoute,
  ApiSystemStatusRoute: ApiSystemStatusRoute,
  ApiSystemTasksRoute: ApiSystemTasksRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiIndexersAggregateProtocolRoute: ApiIndexersAggregateProtocolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
